project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # Ensures R code executes when needed
  eval: true    # Allow R code execution
  echo: false
  
website:
  title: "STA9750 Submission Material"
  description:
    Course Projects for STA9750 at Baruch College
  site-url: "https://jlopez-6.github.io/STA9750-2025-SPRING/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: minty
    toc: false

editor:
  mode: source