project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # Ensures R code executes when needed
  eval: true    # Allow R code execution
  echo: false
  
website:
  title: "STA9750 Submission Material"
  description: "Course Projects for STA9750 at Baruch College"
  site-url: "https://jlopez-6.github.io/STA9750-2025-SPRING/"
  navbar:
    background: primary
    search: false
    left:
      - text: Home
        href: index.html
      - text: CATS Payroll Report
        href: mp01.html
      - text: GTA IV 2025 Greenies
        href: mp02.html
      - text: The Ultimate Playlist
        href: mp03.html
      - text: Political Paradigm Shift
        href: mp04.html
      - text: "Money Talks: Connecticut Real Estate"
        href: individual_report.html
      - text: About Me
        href: about.html
    
format:
  html:
    theme: minty
    toc: false

editor:
  mode: source
